-- populate roles
INSERT INTO roles
VALUES (1, 'USER', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'ACTIVE');
INSERT INTO roles
VALUES (2, 'MODERATOR', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'ACTIVE');
INSERT INTO roles
VALUES (3, 'ADMIN', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'ACTIVE');